#! /bin/bash

# python src/train.py --model=cnn --num_epochs=200 --word_dim=300
# python src/train.py --model=cnn --num_epochs=200 --word_dim=300 --test
# src/scorer.pl data/test_keys.txt data/results.txt

python src/train.py --model=mtl --num_epochs=200 --word_dim=300
python src/train.py --model=mtl --num_epochs=200 --word_dim=300 --test
src/scorer.pl data/test_keys.txt data/results.txt

