#! /bin/bash

# rm data/*.tfrecord
# rm data/*.trim.npy
# rm data/vocab.txt

CUDA_VISIBLE_DEVICES=2 python3  src/train.py  --num_epochs=200 --word_dim=50
# python src/train.py  --num_epochs=200 --word_dim=50 --test
# src/scorer.pl data/test_keys.txt data/results.txt

# python src/train.py  --num_epochs=200 --word_dim=300
# python src/train.py  --num_epochs=200 --word_dim=300 --test
# src/scorer.pl data/test_keys.txt data/results.txt

