#! /bin/bash

# python src/train.py --model=cnn --num_epochs=50
python src/train.py --model=cnn --num_epochs=200 --test
src/scorer.pl data/test_keys.txt data/results.txt

# python src/train.py --model=mtl

